[project]
name = "drpaper"
version = "0.1.0"
description = "DrPaper——中文学术写作 Agent"
readme = "README.md"
authors = [
    { name = "Takamiya-reborn", email = "2196733767@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "arxiv>=2.2.0",
    "latex2mathml>=3.81.1",
    "mathml2omml>=0.0.2",
    "openai>=3.23.0",
    "pylatex>=1.4.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
    "pytest>=8",
]

[project.scripts]
drpaper = "drpaper:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
